//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiClientShared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HttpMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiClientShared.Resources.HttpMessages", typeof(HttpMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA_INVALID.
        /// </summary>
        public static string CaptchaInvalid {
            get {
                return ResourceManager.GetString("CaptchaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAS_SKILL_NOT_FOUND.
        /// </summary>
        public static string HasSkillNotFound {
            get {
                return ResourceManager.GetString("HasSkillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOBBY_NOT_FOUND.
        /// </summary>
        public static string HobbyNotFound {
            get {
                return ResourceManager.GetString("HobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE_IMAGE_INVALID.
        /// </summary>
        public static string ProfileImageInvalid {
            get {
                return ResourceManager.GetString("ProfileImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE_IMAGE_SIZE_INVALID.
        /// </summary>
        public static string ProfileImageSizeInvalid {
            get {
                return ResourceManager.GetString("ProfileImageSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE_NOT_FOUND.
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT_NOT_FOUND.
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION_DUPLICATE.
        /// </summary>
        public static string RegistrationDuplicate {
            get {
                return ResourceManager.GetString("RegistrationDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESPONSIBILITY_ALREADY_AVAILABLE.
        /// </summary>
        public static string ResponsibilityAlreadyAvailable {
            get {
                return ResourceManager.GetString("ResponsibilityAlreadyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESPONSIBILITY_NOT_FOUND.
        /// </summary>
        public static string ResponsibilityNotFound {
            get {
                return ResourceManager.GetString("ResponsibilityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKILL_CATEGORY_ALREADY_EXIST.
        /// </summary>
        public static string SkillCategoryAlreadyAvailable {
            get {
                return ResourceManager.GetString("SkillCategoryAlreadyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKILL_CATEGORY_IMAGE_SIZE_INVALID.
        /// </summary>
        public static string SkillCategoryImageSizeInvalid {
            get {
                return ResourceManager.GetString("SkillCategoryImageSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKILL_CATEGORY_NOT_FOUND.
        /// </summary>
        public static string SkillCategoryNotFound {
            get {
                return ResourceManager.GetString("SkillCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKILL_INVALID.
        /// </summary>
        public static string SkillInvalid {
            get {
                return ResourceManager.GetString("SkillInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKILL_DUPLCATED.
        /// </summary>
        public static string SkillIsDuplicate {
            get {
                return ResourceManager.GetString("SkillIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKILL_NOT_FOUND.
        /// </summary>
        public static string SkillNotFound {
            get {
                return ResourceManager.GetString("SkillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_DESCRIPTION_NOT_FOUND.
        /// </summary>
        public static string UserDescriptionNotFoud {
            get {
                return ResourceManager.GetString("UserDescriptionNotFoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_NOT_FOUND.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
