using System.ComponentModel.DataAnnotations;

namespace ApiClientShared.ViewModel.User
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        /// <summary>
        /// Account password.
        /// </summary>
        [Required]
        public string Password { get; set; }

        /// <summary>
        /// Client capcha code which is generated by Google re-captcha service.
        /// </summary>
        public string ClientCaptchaCode { get; set; }

    }
}